run `echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV` in `setup` step

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -75,7 +75,10 @@ jobs:
           rustup default ${{ matrix.toolchain }}
           rustup target add ${{ matrix.arch }}-unknown-linux-gnu
           rustup component add rustfmt   ### required for the build script to work ###
-          [ "${{ matrix.arch }}" = 'aarch64' ] && sudo apt update && sudo apt install -y g++-aarch64-linux-gnu || :
+          if [ "${{ matrix.arch }}" = 'aarch64' ]; then
+            sudo apt update && sudo apt install -y g++-aarch64-linux-gnu
+            echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV
+          fi
           
           mkdir -p $HOME/.mujoco
           cd $HOME/.mujoco
@@ -94,13 +97,12 @@ jobs:
             cmake ..
             make && sudo make install
           elif [ "${{ matrix.arch }}" = 'aarch64' ]; then
-            echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV
             sudo dpkg --add-architecture arm64
             echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/ports.list
             echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ports.list
             echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ports.list
             echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports noble-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ports.list
-            sudo apt update || :   ### fails to fetch security repositories that don't support arm64, but it doesn't matter ###
+            sudo apt update || :   ### fails to some fetch security repositories that don't support arm64, but it doesn't matter ###
             sudo apt install -y cmake build-essential libwayland-dev:arm64 libxkbcommon-x11-dev:arm64 libgl1-mesa-dev:arm64 libxcursor-dev:arm64 libxi-dev:arm64 libxinerama-dev:arm64 libxrandr-dev:arm64
             sudo apt install -y wayland-protocols
             cmake .. -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
