ignore apt update error

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -96,8 +96,7 @@ jobs:
           elif [ "${{ matrix.arch }}" = 'aarch64' ]; then
             echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV
             sudo dpkg --add-architecture arm64
-            sudo sed -i -e 's/deb http:\/\/security.ubuntu.com/deb [arch=amd64] http:\/\/security.ubuntu.com/g' /etc/apt/sources.list   ### restrict security repository to amd64, as it doesn't support arm64 ###
-            sudo apt update
+            sudo apt update || :   ### fails to fetch security repositories that don't support arm64, but it doesn't matter ###
             sudo apt install -y cmake:arm64 build-essential:arm64 libwayland-dev:arm64 libxkbcommon-x11-dev:arm64 libgl1-mesa-dev:arm64 libxcursor-dev:arm64 libxi-dev:arm64 libxinerama-dev:arm64 libxrandr-dev:arm64
             sudo apt install -y wayland-protocols
             cmake .. -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
